"""add_project_dates_and_tags

Revision ID: 30ed649a8312
Revises: a392a5c15bf7
Create Date: 2025-08-30 19:18:04.470784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30ed649a8312'
down_revision: Union[str, None] = 'a392a5c15bf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('projects', sa.Column('end_date', sa.Date(), nullable=True))
    op.add_column('projects', sa.Column('tags', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'tags')
    op.drop_column('projects', 'end_date')
    op.drop_column('projects', 'start_date')
    # ### end Alembic commands ###
